name: Build ZMK Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ hashFiles('build.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: Build Left
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename Left UF2
        run: cp build/zephyr/zmk.uf2 corne_left.uf2

      - name: Build Right
        run: west build -s zmk/app -b nice_nano_v2 --pristine -- -DSHIELD=corne_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename Right UF2
        run: cp build/zephyr/zmk.uf2 corne_right.uf2

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            corne_left.uf2
            corne_right.uf2
